name: Deploy GitHub Package Registry

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@ricardocrescenti'
      - run: npm install
      - run: npm audit fix
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}